version: "3"
services:
  worker:
    image: proton69/couchbase:enterprise-5.1.0-perftools
    deploy:
      replicas: 1
    environment:
      TYPE: "WORKER"
      COUCHBASE_MASTER: "couchbase-master_master.couchbase-master_couchbase"
      AUTO_REBALANCE: "false"
networks:
  default:
    external:
      name: couchbase-master_couchbase
